### ISSUE TITLE
请问您这个APP是用哪个IDE环境编译的呢。

### ISSUE THREAD

**Issue by yzh979** [Yuanuo/appxi-cbeta-explorer#1]
您好，请问您这个APP是用哪个IDE环境编译的呢。我是个新手，下载了代码。在IntelliJ IDEA环境 下提示appxi-timeago，等文件找不到。

**Comment by Yuanuo** [comment]
IntelliJ IDEA Community 即可。（今天IDEA已经有2021.1的EAP版可以支持JDK16了，推荐！）

Maven依赖中以 appxi- 开头的需要下载这个账号下的其他项目，没有发布到公共仓库，需要自己下载在本地编译安装。

**Comment by yzh979** [comment]
感恩您的及时回复。 目前还有appxi-javafx ，和 appxi-tome 编译出错。请问 jsoup 1.14.2-SNAPSHOT  是从哪里下载的呢？我在https://repo.maven.apache.org/maven2/org/jsoup/jsoup/  只看到1.13.1 版本。并且改这个版本编译一直有出错提示。Failed to execute goal on project appxi-tome: Could not resolve dependencies for project org.appxi:appxi-tome:jar:21.01.24: Failed to collect dependencies at org.jsoup:jsoup:jar:1.13.1: Failed to read artifact descriptor for org.jsoup:jsoup:jar:1.13.1: Could not transfer artifact org.jsoup:jsoup:pom:1.13.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/jsoup/jsoup/1.13.1/jsoup-1.13.1.pom: Malformed reply from SOCKS server -> [Help 1]
To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by Yuanuo** [comment]
jsoup 要用这个 https://github.com/Yuanuo/jsoup 。
appxi-javafx 没有用特殊修改的东西。

看错误是Maven下载的问题。
