### ISSUE TITLE
macOS 上无法打开

### ISSUE THREAD

**Issue by JeffWoo2019** [Yuanuo/appxi-cbeta-explorer#11]
“智悲乐藏” is damaged and can’t be opened. You should move it to the Trash.

![Xnip2023-05-07_11-47-08](https://user-images.githubusercontent.com/66646219/236696820-79d07e59-99a0-45fc-b907-76780176a762.jpg)

<img width="698" alt="image" src="https://user-images.githubusercontent.com/66646219/236696849-7c06e1a5-1ec3-4810-9135-745147a1aa73.png">

**Comment by Yuanuo** [comment]
你好，macOS有时候会这样提示，按网上说法，请尝试在终端执行以下命令试看能否解决：

`xattr -d com.apple.quarantine /Applications/智悲乐藏.app`

**Comment by JeffWoo2019** [comment]
多谢， xattr -cr /Applications/智悲乐藏.app  用了这个，解决了。
