### ISSUE TITLE
建议增加佛光山的词典，或一行佛学词典

### ISSUE THREAD

**Issue by yuqianyi1002** [Yuanuo/appxi-cbeta-explorer#12]
而 一行佛学词典  集成了众多词典，是一个很好的参考。

**Comment by Yuanuo** [comment]
待更新。
词典功能已重写允许用户导入mdx，但暂时还不空做集成测试更新。

**Comment by JeffWoo2019** [comment]
太好了，太感谢了。
目前用您这个app 给我带来了很多方便。

**Comment by Pantyhose-X** [comment]
# 完整的学习过程 
(巴利三藏) 到 (六祖壇經) 到 [(大般若波羅蜜多經)](https://zh.wikisource.org/wiki/%E5%A4%A7%E8%88%AC%E8%8B%A5%E6%B3%A2%E7%BE%85%E8%9C%9C%E5%A4%9A%E7%B6%93) 到 [(CBETA 漢譯南傳大藏經)](https://tripitaka.cbeta.org/N)

[巴利三藏没有完整的 汉译版本](https://ibc.ac.th/ch/sites/default/files/attached/Pali%20Tipitaka%20complete%20list%20(includes%20Commentaries,%20Sub-Commentaries).pdf)

# 巴利三藏 又名 Pali Tipitaka  获取完整的巴利语数字版 有难度。
世界三藏基金会：移交三套巴利三藏版本作为佛法的礼物；即大英图书馆的世界三藏（罗马文版，40 卷）、普密蓬国王版（巴利手稿，40 卷）和诗丽吉王后版（巴利文法，40 卷）。
 ![](https://www.worldtipitaka.net/wp-content/uploads/2019/11/328759.jpg)

**Comment by Yuanuo** [comment]
新发布的24.02.18版已集成此两个词典。
