### ISSUE TITLE
New release Linux compile file

### ISSUE THREAD

**Issue by eBLDR** [Yuanuo/appxi-cbeta-explorer#2]
Hello,

Thank you for your latest release.

Would it be possible to also offer a compiled file (as it was offered in the previous releases) for Linux so that we can run it in Linux systems?

Thanks!

**Comment by Yuanuo** [comment]
Added, thank you for your reminder!

https://github.com/Yuanuo/appxi-cbeta-explorer/releases/tag/21.09.19
