### ISSUE TITLE
Issues detected with the input system

### ISSUE THREAD

**Issue by eBLDR** [Yuanuo/appxi-cbeta-explorer#3]
感謝您的發心，使用後有以下問題：
1. 目前在Linux系統使用（包含Debian 10、Debian 11、lmde 4），使用的中文輸入法是Fcitx新酷音chewing，發現無法輸入中文文字在智悲乐藏中，但是依然能複製現成文字再貼到智悲乐藏。

2. 在經文中搜尋定字串，找出後是否可以將此字串用特殊顏色標示出來？目前的標示不夠突顯。

Thank you

**Comment by Yuanuo** [comment]
你好，关于你的两个问题，请使用新版本程序。新版本（21.10.18）对于你的两个问题：
1，可以在快捷检索时使用拼音（全拼）可以暂时解决掉一些。（全文检索暂时不支持拼音，代价可能比较大）
2，快捷检索和全文检索的结果列表中都有比较明显的高亮显示关键词了。
