### ISSUE TITLE
几点建议和问题

### ISSUE THREAD

**Issue by henrylee0324** [Yuanuo/appxi-cbeta-explorer#7]
谢谢您的付出
目前软体本身已经很好用了
以下提出几点建议和问题

1. 即使选择繁体中文显示，仍有多处以简体中文显示

2. 使用Linux系统，目前有多处仍无法直接输入中文，但可以复制贴上中文

3. Fedora版本的"复制为引用"功能无法使用

4. 目前新增的辞典功能，如果可以自行添加字典、辞典会提高自由度，例如康熙字典等
目前MDict这部份资源很多
https://www.mdict.cn/wp/?lang=zh
格式是.mdd .mdx，开源软体GoldenDict已经有支援这种字典档，如果您愿意可以参考

5. 另外如果可以将辞典以分页方式开启，这样在使用上应当会更方便

6. 如果可以同时在不同面板显示多分页，这样可以方便交互参照
如图所示，这是一款名叫Obsidian的笔记软体，它可以同时显示多分页
https://obsidian.md/

最后再次谢谢您

**Comment by henrylee0324** [comment]
附上相关图片
![分頁](https://user-images.githubusercontent.com/55950712/170704616-e2d668de-db24-4334-9601-432aad0d481a.png)

**Comment by Yuanuo** [comment]
感谢使用和反馈。

> 1. 即使选择繁体中文显示，仍有多处以简体中文显示

原始经藏数据在本程序中默认为“中文繁体（台湾）”，只有在选项中未更改或使用此设置项时，才会保持以原始文本显示，而在程序逻辑中不做任何转换处理。其他“繁体”或“中文繁体（香港）”均会做转换处理，结果是会有差异。

另一方面，该选项不控制主程序界面的文字，只在涉及经藏数据的地方才会做转换处理。

> 2. 使用Linux系统，目前有多处仍无法直接输入中文，但可以复制贴上中文

是的确实之前有这个问题。最近又有用户反馈了这个问题，目前已彻底修复了这个问题，已测试未再发现。
请使用新发布的[22.05.27](https://github.com/Yuanuo/appxi-cbeta-explorer/releases/tag/22.05.27)。

**Comment by Yuanuo** [comment]
> 3. Fedora版本的"复制为引用"功能无法使用

待查。

> 4. 目前新增的辞典功能，如果可以自行添加字典、辞典会提高自由度，例如康熙字典等

关于词典功能。实际上开始时对这个功能并没有设定太高的目标，因为目前市面上有非常多的辞典软件可用，而且它们的词库更丰富。。所以暂时不太确定具体实用价值。
词库的管理维护，可能会提供一个单独的程序来处理增改删等。


> 5. 另外如果可以将辞典以分页方式开启，这样在使用上应当会更方便
> 6. 如果可以同时在不同面板显示多分页，这样可以方便交互参照

之前有想到这个问题，同一词条，不同辞典的内容可能会同时对比查看，所以目前的实现方式是，每一辞典的词条会显示一个单独的窗口，同时在这个窗口中也可以一次查出该词条在所有辞典的内容并全部显示。
通常在查词时，主程序界面中仍然是查词界面并显示着列表，双击每一条目会打开一个单独的窗口，
如果要在不同辞典间做对比查看，可以打开不同的窗口，并自己组织/排列窗口来同时查看。

关于“分页”显示的缺点：
1是不管横向或纵向分页，总会导致可视区域越来越窄的问题；
2是每个词库的名称都比较长，单单要把词库名称显示完整，就要占据很多空间。所以如果分页并同时多排列几个时，连词库名称也看不完整；
3是可能只在大分辨率的屏幕比较可用，对大多数的标准或者稍小屏幕不太适用；

所以目前用每一词库每一词条单一窗口显示，由用户决定需要对比时打开多窗口同时查看。

**Comment by henrylee0324** [comment]
谢谢您的回覆，问题2和3目前在22.05.27中已解决，谢谢。

此外，还有一个功能建议，是否可以就单一经典进行特定词汇全文搜寻。
目前可以设定粗略条件搜寻特定词汇，例如：某作者译者、时代等等。
或是可以在某一卷中搜寻特定词汇，例如：大智度论第50卷。
可否增加单一经典特定词汇全文搜寻，例如：大智度论整部论第1卷到第100卷。

**Comment by Yuanuo** [comment]
感谢反馈。

关于搜索功能的范围问题，目前提供：
1. 页内查找。这是最小粒度，因为根据原始经藏数据的结构，目前每个“页”其实就是“1卷”。
2. 本书内查找。这个就是“卷”的上一级“单一书”或“单一经”。
3. “文件夹”内查找。在左侧典籍树中任何“文件夹/目录”中右键并“从这里搜索”，会搜索该目录下的所有典籍。
4. 全文/全库内查找。

> 可否增加单一经典特定词汇全文搜寻，例如：大智度论整部论第1卷到第100卷。

这个也许是上面第2点的功能？

但是某一部书里限定卷数来搜索，这个没有考虑过实际用途。之前在搜索功能里面不支持限定范围是因为可选范围实在太多。。
我需要重新考虑一下有没有简便的方法，或者限定最多选择10个限定条件。。

**Comment by Yuanuo** [comment]
顺便，
前面你提到的Obsidian这个软件，之前我尝试用过，想用它做一个庞大的知识库，但发现它在搜索方面难以满足需求。

比如目前市面上没有（好用的）基于龙藏的软件，有的基本上是基于网页的纯浏览用的。
所以我想如果把龙藏集成到Obsidian里也许好用，但发现搜索困难。貌似不只是中文方面的问题，可能大量内容也会出现搜索方面的问题。

所以后来就做了一个[Smart Library](https://github.com/Yuanuo/smart-library)的程序，也能实现数据录入（html格式）和强大的全文搜索功能。

如果你需要一个本地可搜索的《乾隆大藏经》可以尝试一下这个程序，我录入的龙藏数据在 [https://github.com/Yuanuo/smartLib-long-zang](https://github.com/Yuanuo/smartLib-long-zang)。（下载/clone到本地，并用Smart Library打开该目录即可浏览阅读，建议全局索引即可搜索）

**Comment by henrylee0324** [comment]
谢谢您的即时回覆，看来是我不太会用，这就是我想的功能。
另外针对特定词汇搜寻的结果显示，如图所示，我个人是比较喜欢cbeta网路版的呈现方式。
此外不确定是否是我个人不会使用，有时我在智悲乐藏点击进入搜寻的特定词汇时，特定词汇不会反白突显，但有时又会正常反白。
再次谢谢您不厌其烦的付出。
![Uploading session-2022-05-28-110010.png…]()

**Comment by henrylee0324** [comment]
![session-2022-05-28-105844](https://user-images.githubusercontent.com/55950712/170807310-2908d98b-a1c3-4e57-b076-a578b3da5ef4.png)

**Comment by henrylee0324** [comment]
![session-2022-05-28-105844 (1)](https://user-images.githubusercontent.com/55950712/170807354-3527d5aa-7b6c-4fbd-b155-d7eba1e06aaa.png)
![session-2022-05-28-110010](https://user-images.githubusercontent.com/55950712/170807357-358dea53-c477-475a-ac67-b3677ffe22c0.png)

**Comment by Yuanuo** [comment]
如果只是高亮词所在的条目前的序号的差别，这个倒是可以优化调整一下显示方式。。目前是随大多数搜索引擎的显示方式用...分隔的。
稍长的文本会随可视宽度折行显示，这一点无法避免，所以它不一定能总是排列得那么好看。

全文搜索的数据粒度方面也有差别。
CBETA官方通常是以“卷”为单位。本程序里面为了方便，粒度更细，大多数的典籍都细化到品，章节目录，或者任何可以单独形成“标题”和“内容”的部分。
这样的“好处”呈现在，比如《高僧传》可以细化成很多个人的内容，此时在“快捷检索”时只需要输入某人名就可直接显示该人相关的条目。
“不太友好”的一点是，因为内容不是完全优化过的而只是原始数据，所以搜索结果中有些标题部分显示为纯数字之类。

另外，在搜索结果中的高亮词上点击，会”打开该经卷并尝试定位到相应位置“。

**Comment by henrylee0324** [comment]
另外，在搜索结果中的高亮词上点击，会”打开该经卷并尝试定位到相应位置“。

這部份經您的解說，我應當可以確認我的使用方式是正確的，我認為這可能是一個bug。我目前使用.deb版本。

**Comment by Yuanuo** [comment]
![image](https://user-images.githubusercontent.com/10892032/170816507-2b03e352-e750-436e-b958-0c033d036832.png)

这部分UI看起来有点异常，你能否说一下桌面分辨率和缩放比例大小？谢谢。

**Comment by henrylee0324** [comment]
![1](https://user-images.githubusercontent.com/55950712/171026111-83ce923e-be8d-4cc9-ad2f-ac3aa46d8d15.png)
![2](https://user-images.githubusercontent.com/55950712/171026119-08abb90d-4e65-4c97-997e-48a3030b1d04.png)

**Comment by Yuanuo** [comment]
已修复
